
import { Token } from "../interfaces/TokenInterface";

export const urbanTokens: Token[] = [
  {
    id: "K1",
    name: "K1 - Edifício Comercial Manhattan Tower",
    symbol: "K1",
    totalSupply: 1,
    fractionPrice: 89.25,
    imageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1632&q=80",
    description: "Imóvel comercial premium localizado no coração financeiro de São Paulo. O Manhattan Tower oferece localização estratégica, infraestrutura moderna e alto potencial de valorização.",
    marketCap: 2800000,
    volume24h: 65000,
    priceChange24h: 5.8,
    totalFractions: 1000,
    availableFractions: 280,
    holders: 620,
    location: "Av. Paulista, São Paulo, SP",
    area: 45,
    propertyType: "Comercial",
    yearBuilt: 2010,
    isWholeProperty: false
  },
  {
    id: "K2",
    name: "K2 - Loja Vila Olímpia Premium",
    symbol: "K2",
    totalSupply: 1,
    fractionPrice: 75.50,
    imageUrl: "https://images.unsplash.com/photo-1556962236-5ec6c921f6c1?auto=format&fit=crop&w=800",
    description: "Loja comercial estrategicamente localizada na Vila Olímpia, um dos bairros mais valorizados de São Paulo. Excelente fluxo de pessoas e visibilidade para seu negócio.",
    marketCap: 1500000,
    volume24h: 120000,
    priceChange24h: 12.3,
    totalFractions: 500,
    availableFractions: 175,
    holders: 125,
    location: "Vila Olímpia, São Paulo, SP",
    area: 80,
    propertyType: "Comercial",
    yearBuilt: 2015,
    isWholeProperty: false
  },
  {
    id: "3",
    name: "Flat Comercial Paulista",
    symbol: "FCPL",
    totalSupply: 1,
    fractionPrice: 89.25,
    imageUrl: "https://images.unsplash.com/photo-1566041510639-8d95a2490bfb?auto=format&fit=crop&w=800",
    description: "Flat comercial na Av. Paulista, com serviços de hotelaria e ótima rentabilidade para investidores. Mobiliado e pronto para locação.",
    marketCap: 2800000,
    volume24h: 65000,
    priceChange24h: 5.8,
    totalFractions: 1000,
    availableFractions: 280,
    holders: 620,
    location: "Av. Paulista, São Paulo, SP",
    area: 45,
    propertyType: "Flat",
    yearBuilt: 2010,
    isWholeProperty: false
  },
  {
    id: "4",
    name: "Loja Centro Histórico",
    symbol: "LCHS",
    totalSupply: 1,
    fractionPrice: 75.50,
    imageUrl: "https://images.unsplash.com/photo-1556962236-5ec6c921f6c1?auto=format&fit=crop&w=800",
    description: "Loja comercial no centro histórico de Belo Horizonte. Excelente fluxo de pessoas e visibilidade para seu negócio.",
    marketCap: 1500000,
    volume24h: 120000,
    priceChange24h: 12.3,
    totalFractions: 500,
    availableFractions: 175,
    holders: 125,
    location: "Centro, Belo Horizonte, MG",
    area: 80,
    propertyType: "Comercial",
    yearBuilt: 1985,
    isWholeProperty: false
  },
  {
    id: "5",
    name: "Galpão Logístico Guarulhos",
    symbol: "GLGU",
    totalSupply: 1,
    fractionPrice: 165.25,
    imageUrl: "https://images.unsplash.com/photo-1625244724120-1fd1d34d00f6?auto=format&fit=crop&w=800",
    description: "Galpão logístico de alto padrão em Guarulhos, próximo ao aeroporto internacional. Ideal para empresas de logística e e-commerce.",
    marketCap: 12000000,
    volume24h: 3500000,
    priceChange24h: -2.7,
    totalFractions: 2000,
    availableFractions: 560,
    holders: 870,
    location: "Guarulhos, São Paulo, SP",
    area: 5000,
    propertyType: "Industrial",
    yearBuilt: 2020,
    isWholeProperty: false
  },
  {
    id: "K3",
    name: "Instituto K Professor Ulisses Vieira",
    symbol: "IKPUV",
    totalSupply: 1,
    fractionPrice: 65.75,
    imageUrl: "/lovable-uploads/3d927806-fff9-4cf1-8af0-3b7e05c7afae.png",
    description: "Loja de manutenção de notebooks e informática localizada em área comercial estratégica. Estabelecimento com mais de 10 anos de atuação em Central de Manutenção de equipamentos eletrônicos.",
    marketCap: 1200000,
    volume24h: 45000,
    priceChange24h: 3.2,
    totalFractions: 800,
    availableFractions: 250,
    holders: 180,
    location: "Centro, São José dos Campos, SP",
    area: 60,
    propertyType: "Comercial",
    yearBuilt: 2010,
    isWholeProperty: false
  }
];
