// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjkzdfdtmhgjhynnmzdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlqa3pkZmR0bWhnamh5bm5temRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMTAzMTEsImV4cCI6MjA2MDc4NjMxMX0.CuCPzfqTKHTDUJop6iWEWlsAxNin7UIdUw8oHRGP4J4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);